parallel-jobs = 1

cli-source = "revanced/revanced-cli"
patches-source = "revanced/revanced-patches"
integrations-source = "revanced/revanced-integrations"

[YouTube]
enabled = true
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
version = "auto"
arch = "all"
included-patches = "'Bypass image region restrictions' 'Bypass URL redirects' 'Change start page' 'Check watch history domain name resolution' 'Disable auto captions' 'Disable fullscreen ambient mode' 'Disable player popup panels' 'Disable precise seeking gesture' 'Disable resuming Shorts on startup' 'Disable rolling number animations' 'Disable suggested video end screen' 'Disable zoom haptics' 'GmsCore support' 'Hide ads' 'Hide endscreen cards' 'Hide info cards' 'Hide layout components' 'Hide player flyout menu items' 'Hide player overlay buttons' 'Hide seekbar' 'Hide Shorts components' 'Hide timestamp' 'Hide video action buttons' 'Miniplayer' 'Navigation buttons' 'Open links externally' 'Remember video quality' 'Remove background playback restrictions' 'Remove player controls background' 'Remove tracking query parameter' 'Remove viewer discretion dialog' 'Restore old video quality menu' 'Return YouTube Dislike' 'Seekbar tapping' 'Seekbar thumbnails' 'Shorts autoplay' 'SponsorBlock' 'Spoof app version' 'Spoof device dimensions' 'Spoof video streams' 'Video ads'"
excluded-patches = "'Alternative thumbnails' 'Always repeat' 'Announcements' 'Change header' 'Copy video URL' 'Custom branding' 'Custom player overlay opacity' 'Downloads' 'Enable debugging' 'Enable slide to seek' 'Enable tablet layout' 'Playback speed' 'Swipe controls' 'Theme' 'Wide searchbar'"
patcher-args = "-OgmsCoreVendorGroupId=app.revanced "

[YouTube-Music]
enabled = true
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
version = "auto"
arch = "both"
included-patches = "'Bypass certificate checks' 'Enable exclusive audio playback' 'GmsCore support' 'Hide 'Get Music Premium' label' 'Hide music video ads' 'Remove background playback restrictions' 'Remove upgrade button'"
excluded-patches = "'Hide category bar' 'Permanent repeat' 'Permanent shuffle'"
patcher-args = "-OgmsCoreVendorGroupId=app.revanced "

[Twitch]
enabled = true
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/twitch-interactive-inc/twitch"
uptodown-dlurl = "https://twitch.en.uptodown.com/android"
version = "auto"
arch = "all"

[TikTok]
enabled = true
build-mode = "apk"
uptodown-dlurl = "https://tik-tok.en.uptodown.com/android"
version = "auto"
arch = "all"
included-patches = "'SIM spoof'"

[TikTok-Musically]
enabled = true
build-mode = "apk"
uptodown-dlurl = "https://tiktok.en.uptodown.com/android"
version = "auto"
arch = "all"
included-patches = "'SIM spoof'"

[Twitter]
enabled = false
build-mode = "apk"
apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
version = "auto"
arch = "all"

[Reddit]
enabled = false
build-mode = "apk"
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"

version = "auto"
arch = "all"

[Google-Photos]
enabled = false
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"
version = "auto"
arch = "both"

[Lightroom]
enabled = false
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/adobe/lightroom"
uptodown-dlurl = "https://adobe-lightroom-mobile.en.uptodown.com/android"
version = "auto"
arch = "arm64-v8a"

[Backdrops]
enabled = false
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/backdrops/backdrops-wallpapers"
uptodown-dlurl = "https://backdrops.en.uptodown.com/android"
version = "auto"
arch = "all"
