cli-source = "revanced/revanced-cli"
patches-source = "revanced/revanced-patches"
integrations-source = "revanced/revanced-integrations"

[YouTube]
enabled = true
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
version = "auto"
build-mode = "apk"
included-patches = "'Announcements' 'Bypass URL redirects' 'Change start page' 'Enable slide to seek' 'GmsCore support' 'Hide ads' 'Minimized playback' 'Navigation buttons' 'Open links externally' 'Remember video quality' 'Remove tracking query parameter' 'Remove viewer discretion dialog' 'Restore old seekbar thumbnails' 'Restore old video quality menu' 'Return YouTube Dislike' 'Seekbar tapping' 'SponsorBlock' 'Spoof app version' 'Spoof client' 'Spoof device dimensions' 'Video ads'"
exclusive-patches = true

[YouTube-Music]
enabled = true
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
version = "auto"
build-mode = "apk"
arch = "both"

[Twitch]
enabled = true
uptodown-dlurl = "https://twitch.en.uptodown.com/android"
version = "auto"
build-mode = "apk"

[TikTok-Musically]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"
version = "auto"
build-mode = "apk"
included-patches = "'SIM spoof'"

[TikTok]
enabled = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok/"
version = "auto"
build-mode = "apk"
included-patches = "'SIM spoof'"
