parallel-jobs = 1

cli-source = "revanced/revanced-cli"
patches-source = "revanced/revanced-patches"
integrations-source = "revanced/revanced-integrations"

cli-version = "latest"
patches-version = "latest"

[YouTube]
enabled = true
build-mode = "apk"
version = "auto"
arch = "all"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
included-patches = "'Bypass image region restrictions' 'Bypass URL redirects' 'Change start page' 'Disable auto captions' 'Disable fullscreen ambient mode' 'Disable player popup panels' 'Disable precise seeking gesture' 'Disable resuming Shorts on startup' 'Disable rolling number animations' 'Disable suggested video end screen' 'Disable zoom haptics' 'Force original audio' 'GmsCore support' 'Hide ads' 'Hide endscreen cards' 'Hide info cards' 'Hide layout components' 'Hide player flyout menu items' 'Hide player overlay buttons' 'Hide seekbar' 'Hide Shorts components' 'Hide timestamp' 'Hide video action buttons' 'Miniplayer' 'Navigation buttons' 'Open links externally' 'Remember video quality' 'Remove background playback restrictions' 'Remove player controls background' 'Remove tracking query parameter' 'Remove viewer discretion dialog' 'Restore old video quality menu' 'Return YouTube Dislike' 'Seekbar tapping' 'Seekbar thumbnails' 'SponsorBlock' 'Spoof app version' 'Spoof device dimensions' 'Spoof video streams' 'Video ads'"
excluded-patches = "'Alternative thumbnails' 'Always repeat' 'Announcements' 'Change header' 'Check watch history domain name resolution' 'Copy video URL' 'Custom branding' 'Custom player overlay opacity' 'Downloads' 'Enable debugging' 'Enable slide to seek' 'Enable tablet layout' 'Open Shorts in regular player' 'Open videos fullscreen' 'Playback speed' 'Shorts autoplay' 'Swipe controls' 'Theme' 'Wide searchbar'"
patcher-args = "-OgmsCoreVendorGroupId=app.revanced "

[YouTube-Music]
enabled = true
build-mode = "apk"
version = "auto"
arch = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
included-patches = "'Bypass certificate checks' 'Enable exclusive audio playback' 'GmsCore support' 'Hide 'Get Music Premium' label' 'Hide music video ads' 'Remove background playback restrictions' 'Remove upgrade button' 'Spoof client'"
excluded-patches = "'Hide category bar' 'Permanent repeat'"
patcher-args = "-OgmsCoreVendorGroupId=app.revanced "

[TikTok-Musically]
enabled = false
build-mode = "apk"
version = "auto"
arch = "all"
uptodown-dlurl = "https://tiktok.en.uptodown.com/android"
included-patches = "'Feed filter' 'Remember clear display' 'Downloads' 'Show seekbar' 'Playback speed' 'Disable login requirement' 'Fix Google login' 'Settings' 'SIM spoof'"
exclusive-patches = true

[TikTok]
enabled = true
build-mode = "apk"
version = "auto"
arch = "all"
uptodown-dlurl = "https://tik-tok.en.uptodown.com/android"
included-patches = "'Feed filter' 'Remember clear display' 'Downloads' 'Show seekbar' 'Playback speed' 'Disable login requirement' 'Fix Google login' 'Settings' 'SIM spoof'"
exclusive-patches = true

[Twitch]
enabled = true
build-mode = "apk"
version = "16.9.1"
arch = "all"
apkmirror-dlurl = "https://www.apkmirror.com/apk/twitch-interactive-inc/twitch"
uptodown-dlurl = "https://twitch.en.uptodown.com/android"
included-patches = "'Block audio ads' 'Block embedded ads' 'Block video ads' 'Show deleted messages' 'Auto claim channel points' 'Settings'"
exclusive-patches = true

[Twitter]
enabled = false
build-mode = "apk"
version = "auto"
arch = "all"
apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"

[Reddit]
enabled = false
build-mode = "apk"
version = "auto"
arch = "all"
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"

[Google-Photos]
enabled = false
build-mode = "apk"
version = "auto"
arch = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"

[Lightroom]
enabled = false
build-mode = "apk"
version = "auto"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/adobe/lightroom"
uptodown-dlurl = "https://adobe-lightroom-mobile.en.uptodown.com/android"

[Backdrops]
enabled = false
build-mode = "apk"
version = "auto"
arch = "all"
apkmirror-dlurl = "https://www.apkmirror.com/apk/backdrops/backdrops-wallpapers"
uptodown-dlurl = "https://backdrops.en.uptodown.com/android"
